//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuvoProcess.Resources.Logging {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InfoResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfoResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JuvoProcess.Resources.Logging.InfoResx", typeof(InfoResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juvo is now running.
        /// </summary>
        public static string BotRunning {
            get {
                return ResourceManager.GetString("BotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating any missing resources....
        /// </summary>
        public static string CreatingMissingResources {
            get {
                return ResourceManager.GetString("CreatingMissingResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing command &apos;{0}&apos;.
        /// </summary>
        public static string ErrorExecCommand {
            get {
                return ResourceManager.GetString("ErrorExecCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing module &apos;{0}&apos;.
        /// </summary>
        public static string ErrorExecModule {
            get {
                return ResourceManager.GetString("ErrorExecModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command.
        /// </summary>
        public static string InvalidCommand {
            get {
                return ResourceManager.GetString("InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching the juvo process....
        /// </summary>
        public static string LaunchingJuvo {
            get {
                return ResourceManager.GetString("LaunchingJuvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading configuration file....
        /// </summary>
        public static string LoadingConfigFile {
            get {
                return ResourceManager.GetString("LoadingConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading plugins....
        /// </summary>
        public static string LoadingPlugins {
            get {
                return ResourceManager.GetString("LoadingPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading users.
        /// </summary>
        public static string LoadingUsers {
            get {
                return ResourceManager.GetString("LoadingUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing command....
        /// </summary>
        public static string ProcessingCommand {
            get {
                return ResourceManager.GetString("ProcessingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down....
        /// </summary>
        public static string ShuttingDown {
            get {
                return ResourceManager.GetString("ShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting bots....
        /// </summary>
        public static string StartingBots {
            get {
                return ResourceManager.GetString("StartingBots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting the web server....
        /// </summary>
        public static string StartingWebServer {
            get {
                return ResourceManager.GetString("StartingWebServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping bots....
        /// </summary>
        public static string StoppingBots {
            get {
                return ResourceManager.GetString("StoppingBots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping web server....
        /// </summary>
        public static string StoppingWebServer {
            get {
                return ResourceManager.GetString("StoppingWebServer", resourceCulture);
            }
        }
    }
}
